# Site settings
title: "Informática, Matemática e afins"
author: "João Vitor Rodrigues da Silva"
description: "Esse é um blog sobre desenvolvimento de softwares, matemática, estatística, e outros assuntos relacionados ao curso de Ciência da Computação."
keywords: "Ciência da Computação, Matemática, Software, Website, Estatística, Cálculo, Git, Github, Ruby, Python, Haskell, Linux"
biography: "Eu sou graduando de Ciência da Computação pela <a href='http://www.ufal.edu.br/'>Universidade Federal de Alagoas</a>, técnico em Informática pelo <a href='https://www2.ifal.edu.br/'>Instituto Federal de Alagoas</a>, desenvolvedor web na <a href='https://plussoft.com.br'>PlusSoft</a>, entusiasta <a href='https://github.com/tkovs'>opensource</a>, e agora escritor em um blog."
colophon: "© 2018 João Vitor Rodrigues da Silva.<br>Conteúdo sobre <a href='https://mit-license.org/'>MIT License</a>.<br>Este site está hospedado no <a href='https://pages.github.com/'>Github Pages</a> e foi baseado no site do <a href='http://hugosereno.eu/'>Hugo Sereno</a> usando <a href='https://jekyllrb.com/'>Jekyll</a> e <a href='http://getbootstrap.com'>Bootstrap</a>."

baseurl: ""
url: "http://tkovs.me"

# twitter_username:
github_username: tkovs
linkedin_username: tkovs
facebook_username: joaovitorIFAL
instagram_username: _tkovs
# 500px_username:

google-analytics: UA-69060-5
disqus_shortname: tkovsblog

simple_search: http://google.com/search
markdown: kramdown
highlighter: pygments
permalink: /blog/:year/:month/:day/:title/

plugins:
- jekyll-sitemap
