url: http://tkovs.github.io
#url: http://localhost:4000

harmony:
  name: tkovs
  description: #Um blog sobre mim e o que mais eu achar interessante
  meta_description: > # 
      Apenas um blog sobre mim, música, programação, as pessoas e o que mais
      me der na telha, flw.
  basetheme: theme-base-01
  author:
    name: Vitor Rodrigues
    email: victor.rdg@hotmail.com
    url: http://tkovs.github.io

  google_analytics_key: UA-76526417-1
  disqus_shortname: tkovsblog

  social: 
    github: tkovs
    twitter: _tkovs
    facebook: joaovitorIFAL
  show_disclaimer: false

markdown:    kramdown
highlighter: pygments 

permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - vendor

sass:
    sass_dir: assets/css/_sass
    style: :compressed
